- name: Install Database Packages
  when: ansible_facts['hostname']  == "database"
  apt:
    name: "{{ database_packages }}"
    state: latest

- name: Install Database2 Packages
  when: ansible_facts['hostname']  == "database2"
  yum:
    name: "{{ database_packages }}"
    state: latest